[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ethers>=0.1.1",
    "python-dotenv>=1.1.1",
    "uagents>=0.22.10",
]
